### ISSUE TITLE
Infografia componentes y librerias

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/infografia-de-las-librerias-Yeim1129#2]
![J Manuel_Hernandez A_Tópicos__Infografia componentes y librerias]
(https://user-images.githubusercontent.com/79933243/114765340-a9ecfc80-9d2a-11eb-87fc-26119f050c2c.png)

**Comment by JazminloRI** [comment]
[RÚBRICA PARA EVALUAR UNA INFOGRAFÍA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Yeim1129/files/6359909/RUBRICA.PARA.EVALUAR.UNA.INFOGRAFIA.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
